---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:LeajD/AWS-Projects.git
  sshPrivateKey: |
  insecure: "false"
  enableLfs: "true"