---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:LeajD/AWS-Projects.git
  sshPrivateKey: | #put your private key here in a secure manner (use secrets manager in aws or sealed secrets in k8s)
  insecure: "false"
  enableLfs: "true"