#app of apps in argocd for recursive directory 'dev' resources stored in git to deploy in k8s

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io #finalizer to clean up the resources
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: gitops-merging/apps/envs/dev #make sure to match git repo dir path
    repoURL: git@github.com:LeajD/AWS-Projects.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=Foreground
    - PruneLast=true