version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # Note: CodeDeploy overrides the TaskDefinition property using your imagedefinitions.json artifact
        TaskDefinition: arn:aws:ecs:us-east-1:703671893205:task-definition/my-ecs-task-bluegreen:39 #"taskdefinition.json" #"imagedefinitions.json"
        LoadBalancerInfo:
          ContainerName: "my-docker-repo"  # Must match the container name defined in your task definition
          ContainerPort: 80